<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>OrderFlow.BuildingBlocks</RootNamespace>
    <AssemblyName>OrderFlow.BuildingBlocks</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
