<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>OrderFlow.Orders.Api</RootNamespace>
    <AssemblyName>OrderFlow.Orders.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orders.Infrastructure\OrderFlow.Orders.Infrastructure.csproj" />
    <ProjectReference Include="..\Orders.Domain\OrderFlow.Orders.Domain.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\OrderFlow.BuildingBlocks.csproj" />
  </ItemGroup>

</Project>
