<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>OrderFlow.Orders.Api</RootNamespace>
    <AssemblyName>OrderFlow.Orders.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orders.Infrastructure\OrderFlow.Orders.Infrastructure.csproj" />
  </ItemGroup>

</Project>
